spring:
  application:
    name: expense-tracker

  datasource:
    url: jdbc:mysql://localhost:3306/expense
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8087
  servlet:
    context-path : /expense

logging:
  level:
    org.springframework.web: DEBUG

